MATCHD-46: deployment Dockerfile

diff --git a/docker/deployment/run-docker-compose b/docker/deployment/run-docker-compose
--- a/docker/deployment/run-docker-compose
+++ b/docker/deployment/run-docker-compose
@@ -2,90 +2,106 @@
 
 set -e
 
-echo $PWD
+if [[ -z "${DOTENV}" ||
+      -z "${COMPOSE_PROJECT_NAME}" ||
+      -z "${COMPOSE_ACTION}" ||
+      -z "${IMAGE}" ||
+      -z "${DJANGO_SETTINGS_MODULE}" ||
+      -z "${DJANGO_SECRET_KEY}" ||
+      -z "${DJANGO_GRAPHIQL_ENABLED}" ||
+      -z "${FRONTEND_URL}" ||
+      -z "${APP_DOMAIN}" ||
+      -z "${APP_CSRF_COOKIE_DOMAIN}" ||
+      -z "${WAGTAIL_SITE_NAME}" ||
+      -z "${DJANGO_DB_NAME}" ||
+      -z "${DJANGO_DB_USER}" ||
+      -z "${DJANGO_DB_PW}" ||
+      -z "${DJANGO_ELASTIC_SEARCH_URL}" ||
+      -z "${DJANGO_ELASTIC_SEARCH_USER}" ||
+      -z "${DJANGO_ELASTIC_SEARCH_PASSWORD}" ||
+#      -z "${DJANGO_EMAIL}" ||
+#      -z "${DJANGO_EMAIL_HOST}" ||
+#      -z "${DJANGO_EMAIL_PORT}" ||
+#      -z "${DJANGO_EMAIL_HOST_USER}" ||
+#      -z "${DJANGO_EMAIL_HOST_PASSWORD}" ||
+#      -z "${DJANGO_EMAIL_SUBJECT_PREFIX}" ||
+      -z "${LAST}" ]]
+then
+    echo "ERROR: A required environment variable is not set" >&2
+    echo " " >&2
+    echo "Docker:" >&2
+    echo "    DOTENV: ${DOTENV}" >&2
+    echo "    COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}" >&2
+    echo "    COMPOSE_ACTION: ${COMPOSE_PROJECT_NAME}" >&2
+    echo "    IMAGE: ${IMAGE}" >&2
+    echo "Django:" >&2
+    echo "    DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}" >&2
+    echo "    DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}" >&2
+    echo "    DJANGO_GRAPHIQL_ENABLED: ${DJANGO_GRAPHIQL_ENABLED}" >&2
+    echo "    FRONTEND_URL: ${FRONTEND_URL}" >&2
+    echo "    APP_DOMAIN: ${APP_DOMAIN}" >&2
+    echo "    APP_CSRF_COOKIE_DOMAIN: ${APP_CSRF_COOKIE_DOMAIN}" >&2
+    echo "    WAGTAIL_SITE_NAME: ${WAGTAIL_SITE_NAME}" >&2
+    echo "Database:" >&2
+    echo "    DJANGO_DB_NAME: ${DJANGO_DB_NAME}" >&2
+    echo "    DJANGO_DB_USER: ${DJANGO_DB_USER}" >&2
+    if [ -z "${DJANGO_DB_PW}" ]
+    then
+      echo "    DJANGO_DB_PW: ${DJANGO_DB_PW}" >&2
+    else
+      echo "    DJANGO_DB_PW: *****" >&2
+    fi
+    echo "Elasticsearch:" >&2
+    echo "    DJANGO_ELASTIC_SEARCH_URL: ${DJANGO_ELASTIC_SEARCH_URL}" >&2
+    echo "    DJANGO_ELASTIC_SEARCH_USER: ${DJANGO_ELASTIC_SEARCH_USER}" >&2
+    if [ -z "${DJANGO_ELASTICSEARCH_PASSWORD}" ]
+    then
+      echo "    DJANGO_ELASTIC_SEARCH_PASSWORD: ${DJANGO_ELASTIC_SEARCH_PASSWORD}" >&2
+    else
+      echo "    DJANGO_ELASTIC_SEARCH_PASSWORD: *****" >&2
+    fi
+#    echo "Email:" >&2
+#    echo "    DJANGO_EMAIL: ${DJANGO_EMAIL}" >&2
+#    echo "    DJANGO_EMAIL_HOST: ${DJANGO_EMAIL_HOST}" >&2
+#    echo "    DJANGO_EMAIL_PORT: ${DJANGO_EMAIL_PORT}" >&2
+#    echo "    DJANGO_EMAIL_HOST_USER: ${DJANGO_EMAIL_HOST_USER}" >&2
+#    if [ -z "${DJANGO_EMAIL_HOST_PASSWORD}" ]
+#    then
+#      echo "    DJANGO_EMAIL_HOST_PASSWORD: ${DJANGO_EMAIL_HOST_PASSWORD}" >&2
+#    else
+#      echo "    DJANGO_EMAIL_HOST_PASSWORD: *****" >&2
+#    fi
+#    echo "    DJANGO_EMAIL_SUBJECT_PREFIX: ${DJANGO_EMAIL_SUBJECT_PREFIX}" >&2
 
-echo "Setup docker-compose" >&2
-echo "--------------------" >&2
-echo "    CI_PROJECT_ID: ${CI_PROJECT_ID}" >&2
-echo "    CI_PROJECT_NAME: ${CI_PROJECT_NAME}" >&2
-echo "    CI_COMMIT_REF_NAME: ${CI_COMMIT_REF_NAME}" >&2
-echo "    CI_COMMIT_REF_SLUG: ${CI_COMMIT_REF_SLUG}" >&2
-echo "    COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}" >&2
-echo "    COMPOSE_ACTION: ${COMPOSE_ACTION}" >&2
-echo "    IMAGE: ${IMAGE}" >&2
+    exit 1
+fi
 
-echo "Environment" >&2
-echo "-----------" >&2
-echo "    DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}" >&2
-echo "    DJANGO_DB_NAME: ${DJANGO_DB_NAME}" >&2
-echo "    DJANGO_DB_USER: ${DJANGO_DB_USER}" >&2
-echo "    DJANGO_ELASTIC_SEARCH_URL: ${DJANGO_ELASTIC_SEARCH_URL}" >&2
-echo "    DJANGO_EMAIL: ${DJANGO_EMAIL}" >&2
-echo "    DJANGO_EMAIL_HOST: ${DJANGO_EMAIL_HOST}" >&2
-echo "    DJANGO_EMAIL_PORT: ${DJANGO_EMAIL_PORT}" >&2
-#echo "    DJANGO_EMAIL_HOST_PASSWORD: ${DJANGO_EMAIL_HOST_PASSWORD}" >&2
-echo "    DJANGO_EMAIL_HOST_USER: ${DJANGO_EMAIL_HOST_USER}" >&2
-echo "    DJANGO_EMAIL_SUBJECT_PREFIX: ${DJANGO_EMAIL_SUBJECT_PREFIX}" >&2
-echo "    DJANGO_GRAPHIQL_ENABLED: ${DJANGO_GRAPHIQL_ENABLED}" >&2
-echo "    FRONTEND_URL: ${FRONTEND_URL}" >&2
-echo "    APP_DOMAIN: ${APP_DOMAIN}" >&2
-echo "    APP_CSRF_COOKIE_DOMAIN: ${APP_CSRF_COOKIE_DOMAIN}" >&2
-echo "    WAGTAIL_SITE_NAME: ${WAGTAIL_SITE_NAME}" >&2
-
-export DOCKER_GATEWAY_HOST="`/sbin/ip route|awk '/default/ { print $3 }'`"
-export DOCKER_GATEWAY_HOST_2="`hostname -I |awk '{print $1}'  `"
-
-echo "    DOCKER_GATEWAY_HOST: ${DOCKER_GATEWAY_HOST}" >&2
-echo "    DOCKER_GATEWAY_HOST_2: ${DOCKER_GATEWAY_HOST_2}" >&2
+echo "Writing ${DOTENV}..."
 
 export TRAEFIK_ROUTER_NAME="api-${COMPOSE_PROJECT_NAME}"
 
-echo "    TRAEFIK_ROUTER_NAME: ${TRAEFIK_ROUTER_NAME}" >&2
-
-if [[ ! -f "docker-compose.yml" ]]
-then
-    echo "Creating 'docker-compse.yml' template…"
-    cat <<EOF >docker-compose.yml
----
-version: '3.8'
-
-services:
-  web:
-    image: ${IMAGE}
-    labels:
-      - "traefik.enable=true"
-      - "traefik.http.routers.${TRAEFIK_ROUTER_NAME}.rule=Host(\`${APP_DOMAIN}\`)"
-    environment:
-      DJANGO_SETTINGS_MODULE: '${DJANGO_SETTINGS_MODULE}'
-      DJANGO_DB_NAME: '${DJANGO_DB_NAME}'
-      DJANGO_DB_USER: '${DJANGO_DB_USER}'
-      DJANGO_DB_PW: '${DJANGO_DB_PW}'
-      DJANGO_ELASTIC_SEARCH_URL: '${DJANGO_ELASTIC_SEARCH_URL}'
-      DJANGO_EMAIL: '${DJANGO_EMAIL}'
-#      DJANGO_EMAIL_HOST: '${DJANGO_EMAIL_HOST}'
-#      DJANGO_EMAIL_PORT: '${DJANGO_EMAIL_PORT}'
-#      DJANGO_EMAIL_HOST_PASSWORD: '${DJANGO_EMAIL_HOST_PASSWORD}'
-#      DJANGO_EMAIL_HOST_USER: '${DJANGO_EMAIL_HOST_USER}'
-      DJANGO_EMAIL_SUBJECT_PREFIX: '${DJANGO_EMAIL_SUBJECT_PREFIX}'
-      DJANGO_GRAPHIQL_ENABLED: '${DJANGO_GRAPHIQL_ENABLED}'
-      FRONTEND_URL: '${FRONTEND_URL}'
-      APP_DOMAIN: '${APP_DOMAIN}'
-      APP_CSRF_COOKIE_DOMAIN: '${APP_CSRF_COOKIE_DOMAIN}'
-      WAGTAIL_SITE_NAME: '${WAGTAIL_SITE_NAME}'
-      DJANGO_SECRET_KEY: '${DJANGO_SECRET_KEY}'
-    volumes:
-      - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock
-    networks:
-      matchd_matchd:
-        aliases:
-          - ${APP_DOMAIN}
-
-networks:
-  matchd_matchd:
-    external: true
-EOF
-fi
-
+echo "DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}" > $DOTENV
+echo "DJANGO_DB_NAME=${DJANGO_DB_NAME}" >> $DOTENV
+echo "IMAGE=${IMAGE}" >> $DOTENV
+echo "DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}" >> $DOTENV
+echo "DJANGO_GRAPHIQL_ENABLED=${DJANGO_GRAPHIQL_ENABLED}" >> $DOTENV
+echo "FRONTEND_URL=${FRONTEND_URL}" >> $DOTENV
+echo "APP_DOMAIN=${APP_DOMAIN}" >> $DOTENV
+echo "APP_CSRF_COOKIE_DOMAIN=${APP_CSRF_COOKIE_DOMAIN}" >> $DOTENV
+echo "WAGTAIL_SITE_NAME=${WAGTAIL_SITE_NAME}" >> $DOTENV
+echo "DJANGO_DB_NAME=${DJANGO_DB_NAME}" >> $DOTENV
+echo "DJANGO_DB_USER=${DJANGO_DB_USER}" >> $DOTENV
+echo "DJANGO_DB_PW=${DJANGO_DB_PW}" >> $DOTENV
+echo "DJANGO_ELASTIC_SEARCH_URL=${DJANGO_ELASTIC_SEARCH_URL}" >> $DOTENV
+echo "DJANGO_ELASTIC_SEARCH_USER=${DJANGO_ELASTIC_SEARCH_USER}" >> $DOTENV
+echo "DJANGO_ELASTIC_SEARCH_PASSWORD=${DJANGO_ELASTIC_SEARCH_PASSWORD}" >> $DOTENV
+echo "DJANGO_EMAIL=${DJANGO_EMAIL}" >> $DOTENV
+echo "DJANGO_EMAIL_HOST=${DJANGO_EMAIL_HOST}" >> $DOTENV
+echo "DJANGO_EMAIL_PORT=${DJANGO_EMAIL_PORT}" >> $DOTENV
+echo "DJANGO_EMAIL_HOST_USER=${DJANGO_EMAIL_HOST_USER}" >> $DOTENV
+echo "DJANGO_EMAIL_HOST_PASSWORD=${DJANGO_EMAIL_HOST_PASSWORD}" >> $DOTENV
+echo "DJANGO_EMAIL_SUBJECT_PREFIX=${DJANGO_EMAIL_SUBJECT_PREFIX}" >> $DOTENV
+echo "TRAEFIK_ROUTER_NAME=${TRAEFIK_ROUTER_NAME}" >> $DOTENV
 
 case "${COMPOSE_ACTION}" in
 
